//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROMVault2.RVRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RVRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckPassword", ReplyAction="http://tempuri.org/IService1/CheckPasswordResponse")]
        string CheckPassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendUser", ReplyAction="http://tempuri.org/IService1/SendUserResponse")]
        string SendUser(string username, string email, int version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendUser1", ReplyAction="http://tempuri.org/IService1/SendUser1Response")]
        string SendUser1(string username, string email, string version, int subversion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLatestVersion", ReplyAction="http://tempuri.org/IService1/GetLatestVersionResponse")]
        int GetLatestVersion(int versionNow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLatestVersion1", ReplyAction="http://tempuri.org/IService1/GetLatestVersion1Response")]
        string GetLatestVersion1(string version, int subversion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUpdateLink", ReplyAction="http://tempuri.org/IService1/GetUpdateLinkResponse")]
        string GetUpdateLink();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUpdateLink1", ReplyAction="http://tempuri.org/IService1/GetUpdateLink1Response")]
        string GetUpdateLink1(string version, int subversion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendErrorMessage", ReplyAction="http://tempuri.org/IService1/SendErrorMessageResponse")]
        void SendErrorMessage(string username, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendErrorMessage1", ReplyAction="http://tempuri.org/IService1/SendErrorMessage1Response")]
        void SendErrorMessage1(string username, string email, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendErrorMessage2", ReplyAction="http://tempuri.org/IService1/SendErrorMessage2Response")]
        void SendErrorMessage2(string username, string email, int version, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendErrorMessage3", ReplyAction="http://tempuri.org/IService1/SendErrorMessage3Response")]
        void SendErrorMessage3(string username, string email, string version, int subversion, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendDATErrorMessage2", ReplyAction="http://tempuri.org/IService1/SendDATErrorMessage2Response")]
        void SendDATErrorMessage2(string username, string email, int version, string error, string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendDATErrorMessage3", ReplyAction="http://tempuri.org/IService1/SendDATErrorMessage3Response")]
        void SendDATErrorMessage3(string username, string email, string version, int subversion, string error, string filename);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ROMVault2.RVRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ROMVault2.RVRef.IService1>, ROMVault2.RVRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckPassword(string username, string password) {
            return base.Channel.CheckPassword(username, password);
        }
        
        public string SendUser(string username, string email, int version) {
            return base.Channel.SendUser(username, email, version);
        }
        
        public string SendUser1(string username, string email, string version, int subversion) {
            return base.Channel.SendUser1(username, email, version, subversion);
        }
        
        public int GetLatestVersion(int versionNow) {
            return base.Channel.GetLatestVersion(versionNow);
        }
        
        public string GetLatestVersion1(string version, int subversion) {
            return base.Channel.GetLatestVersion1(version, subversion);
        }
        
        public string GetUpdateLink() {
            return base.Channel.GetUpdateLink();
        }
        
        public string GetUpdateLink1(string version, int subversion) {
            return base.Channel.GetUpdateLink1(version, subversion);
        }
        
        public void SendErrorMessage(string username, string error) {
            base.Channel.SendErrorMessage(username, error);
        }
        
        public void SendErrorMessage1(string username, string email, string error) {
            base.Channel.SendErrorMessage1(username, email, error);
        }
        
        public void SendErrorMessage2(string username, string email, int version, string error) {
            base.Channel.SendErrorMessage2(username, email, version, error);
        }
        
        public void SendErrorMessage3(string username, string email, string version, int subversion, string error) {
            base.Channel.SendErrorMessage3(username, email, version, subversion, error);
        }
        
        public void SendDATErrorMessage2(string username, string email, int version, string error, string filename) {
            base.Channel.SendDATErrorMessage2(username, email, version, error, filename);
        }
        
        public void SendDATErrorMessage3(string username, string email, string version, int subversion, string error, string filename) {
            base.Channel.SendDATErrorMessage3(username, email, version, subversion, error, filename);
        }
    }
}
